#! /bin/sh



$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10  

bspc config border_width         0
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Règle pour la fenêtre de déplacement de Polybar
bspc rule -a '*:polybar-hide' state=floating hidden=on layer=above


# Autostart
sxhkd & 
